[platformio]
src_dir = firmware/teensy

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

upload_protocol = teensy-cli
monitor_speed = 1000000

build_flags =
  -Wall
  -Wextra

lib_deps =
  https://github.com/sparkfun/SparkFun_LSM6DSV16X_Arduino_Library.git
  https://github.com/bluerobotics/BlueRobotics_MS5837_Library.git

[env:teensy41_debug]
extends = env:teensy41
build_flags =
  ${env:teensy41.build_flags}
  -DSERIAL_DEBUG=1
