[platformio]
src_dir = firmware/teensy

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

monitor_speed = 1000000

build_flags =
  -Wall
  -Wextra

lib_deps =
  https://github.com/sparkfun/SparkFun_LSM6DSV16X_Arduino_Library.git
  https://github.com/bluerobotics/BlueRobotics_MS5837_Library.git
