"""Global configuration constants for Albacore Jetson stack."""

from __future__ import annotations

# Serial configuration
CONTROL_SERIAL_PORT = "/dev/ttyACM0"
AUDIO_SERIAL_PORT = "/dev/ttyACM1"
CONTROL_BAUD = 115200
AUDIO_BAUD = 2_000_000
SERIAL_TIMEOUT_S = 0.01

# Network configuration
UDP_LISTEN_HOST = "0.0.0.0"
UDP_LISTEN_PORT = 5005
JETSON_IP = "192.168.1.50"
LAPTOP_IP = "192.168.1.10"
UDP_RECV_BUFFER = 4096

# Control loop and watchdog
MAIN_LOOP_HZ = 20.0
MAIN_LOOP_DT = 1.0 / MAIN_LOOP_HZ
WATCHDOG_TIMEOUT_S = 0.5

# Camera / vision
CAMERA_INDEX = 0
YOLO_MODEL_NAME = "yolov8n.pt"
VISION_CONF_THRESHOLD = 0.25
VISION_IOU_THRESHOLD = 0.45

# Audio configuration
AUDIO_SAMPLE_RATE_HZ = 20_000
AUDIO_CLASSIFIER_SAMPLE_RATE_HZ = 16_000
AUDIO_CHUNK_SECONDS = 0.25
AUDIO_CHUNK_SAMPLES = int(AUDIO_SAMPLE_RATE_HZ * AUDIO_CHUNK_SECONDS)
AUDIO_BINARY_MODE = False

# Hydrophone array geometry (meters): front-left, front-right, rear-left, rear-right
ARRAY_GEOMETRY = [
    (-0.075, 0.075, 0.0),
    (0.075, 0.075, 0.0),
    (-0.075, -0.075, 0.0),
    (0.075, -0.075, 0.0),
]
SOUND_SPEED_MPS = 1480.0

# Navigation gains and defaults
WAYPOINT_KP = 1.5
WAYPOINT_KI = 0.0
WAYPOINT_KD = 0.2
WAYPOINT_CRUISE_THRUSTER = 45
WAYPOINT_STOP_RADIUS_M = 2.0

TARGET_FOLLOW_RUDDER_KP = 60.0
TARGET_FOLLOW_THRUSTER_KP = 60.0
TARGET_DESIRED_AREA_RATIO = 0.08
TARGET_LOST_FRAMES_HOLD = 8
TARGET_LOST_FRAMES_STOP = 20
TARGET_HOLD_THRUSTER = 20

DEPTH_KP = 3.0
DEPTH_KI = 0.0
DEPTH_KD = 0.2
DEPTH_DEADBAND_M = 0.10

# Actuator limits
THRUSTER_MIN = -100
THRUSTER_MAX = 100
RUDDER_MIN_DEG = -45
RUDDER_MAX_DEG = 45
ELEVATOR_MIN_DEG = -45
ELEVATOR_MAX_DEG = 45

# Ballast command values
BALLAST_ASCEND = -1
BALLAST_STOP = 0
BALLAST_DESCEND = 1

# Mock data defaults
MOCK_BATTERY_START_V = 12.6
MOCK_BATTERY_END_V = 11.0
MOCK_BATTERY_DRAIN_V_PER_S = 0.001
MOCK_AUDIO_TONE_HZ = 550.0
MOCK_AUDIO_AMPLITUDE = 0.8
MOCK_HEADING_RATE_DEG_PER_S = 8.0
